-- migrate:up
-- Cutover from v1 schema (collector + bot) to squawk event-driven architecture.
--
-- What this migration does:
--   1. Add last_seen to sightings with backfill
--   2. Drop enrichment columns from aircraft (data is re-generated by EnrichmentActor)
--   3. Truncate digests (old rows are JSON blobs from the old Pydantic model; re-generated)
--
-- What is lost and acceptable:
--   - Enrichment scores and annotations (re-generated within hours of cutover)
--   - Cached digest text (new digest generated on next Sunday or via /debug)
--   - callsign_routes (re-fetched during enrichment)

-- Step 1: Add last_seen to sightings with backfill.
-- Backfill logic: closed sightings use ended_at; any open sightings (orphaned
-- from the old collector) use started_at as a conservative approximation.
-- close_open_sightings() runs on squawk startup anyway, so open rows are
-- immediately closed and their last_seen value is never read for gap detection.
ALTER TABLE sightings ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ;
UPDATE sightings SET last_seen = COALESCE(ended_at, started_at) WHERE last_seen IS NULL;
ALTER TABLE sightings ALTER COLUMN last_seen SET NOT NULL;

-- Step 2: Drop enrichment columns from aircraft.
-- These are moved to enriched_aircraft (owned by EnrichmentRepository).
ALTER TABLE aircraft
    DROP COLUMN IF EXISTS registration,
    DROP COLUMN IF EXISTS type,
    DROP COLUMN IF EXISTS operator,
    DROP COLUMN IF EXISTS flag,
    DROP COLUMN IF EXISTS fetched_at,
    DROP COLUMN IF EXISTS story_score,
    DROP COLUMN IF EXISTS story_tags,
    DROP COLUMN IF EXISTS lm_annotation,
    DROP COLUMN IF EXISTS enriched_at;

-- Step 3: Truncate digests — old rows use a different serialization format.
TRUNCATE TABLE digests;

-- migrate:down

-- Reverse step 3: nothing to restore (digest content is regenerated)

-- Reverse step 2: re-add enrichment columns to aircraft
ALTER TABLE aircraft
    ADD COLUMN IF NOT EXISTS registration  TEXT,
    ADD COLUMN IF NOT EXISTS type          TEXT,
    ADD COLUMN IF NOT EXISTS operator      TEXT,
    ADD COLUMN IF NOT EXISTS flag          TEXT,
    ADD COLUMN IF NOT EXISTS fetched_at    TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS story_score   INT,
    ADD COLUMN IF NOT EXISTS story_tags    TEXT[]      NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS lm_annotation TEXT,
    ADD COLUMN IF NOT EXISTS enriched_at   TIMESTAMPTZ;

-- Reverse step 1: drop last_seen from sightings
ALTER TABLE sightings DROP COLUMN IF EXISTS last_seen;
